---
- name: Copy /etc/sysctl.conf to bckp directory
  copy:
    src: /etc/sysctl.conf
    dest: '/root/backp_{{ date }}/sysctl.conf'
    owner: root
    group: root
    mode: '0644'

- name: configure /etc/sysctl.conf
  template:
    src: sysctl.j2
    dest: /etc/sysctl.conf
    group: root
    owner: root
    mode: '0644'

- name: reload changes
  shell: sysctl -p /etc/sysctl.conf
